apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: anmolpreet7/projects:8
        name: flaskdemo
        resources: {}
status: {}
---
##apiVersion: v1
##kind: Service
##metadata:
  ##name: lb-service
  ##labels:
    ##app: lb-service
##spec:
  ##type: LoadBalancer
  ##ports:
  ##- port: 80
    ##targetPort: 5000
  ##selector:
    ##app: flaskdemo

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app:  lb-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: flaskdemo
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      ##nodePort: 30007
